// Code generated by catalog/gen.py from catalog/catalog.json. DO NOT EDIT.

// Package catalog is the fixed list of standard things a household trades.
//
// A listing stores a Code - a uint16 - instead of a title, which is the
// point: the text lives in flash as a compile-time constant rather than in
// the 12KiB RAM arena, so a listing for a standard thing costs two bytes
// and a listing with a custom title costs what it always did.
//
// Codes are permanent. Never renumber or reuse one: a code is what the
// ledger stores, and an old record carrying a reused code would silently
// mean something new.
package catalog

// Version of the catalog data these tables were generated from.
const Version = 1

// Category groups items for browsing.
type Category struct {
	ID   uint8
	Slug string
	Name string
}

// Item is one standard thing. Currency and MinorUnits are set only on the
// entries that stand for real money, e.g. "$5 of real cash".
type Item struct {
	Code       uint16
	Cat        uint8
	Name       string
	Currency   string
	MinorUnits int64
}

// Categories, ordered by ID.
var Categories = [...]Category{
	{ID: 1, Slug: "chores", Name: "Chores"},
	{ID: 2, Slug: "kitchen", Name: "Kitchen & food"},
	{ID: 3, Slug: "outdoor", Name: "Outdoor & yard"},
	{ID: 4, Slug: "pets", Name: "Pets"},
	{ID: 5, Slug: "screen", Name: "Screen time & games"},
	{ID: 6, Slug: "toys", Name: "Toys & things"},
	{ID: 7, Slug: "school", Name: "School & learning"},
	{ID: 8, Slug: "favours", Name: "Favours & help"},
	{ID: 9, Slug: "treats", Name: "Treats & privileges"},
	{ID: 10, Slug: "money", Name: "Money & allowance"},
}

// Items, ordered by Code so Lookup can binary search.
var Items = [...]Item{
	{Code: 101, Cat: 1, Name: "Do the dishes"},
	{Code: 102, Cat: 1, Name: "Load the dishwasher"},
	{Code: 103, Cat: 1, Name: "Empty the dishwasher"},
	{Code: 104, Cat: 1, Name: "Take out the trash"},
	{Code: 105, Cat: 1, Name: "Take out the recycling"},
	{Code: 106, Cat: 1, Name: "Vacuum the stairs"},
	{Code: 107, Cat: 1, Name: "Vacuum the living room"},
	{Code: 108, Cat: 1, Name: "Vacuum the whole house"},
	{Code: 109, Cat: 1, Name: "Sweep the kitchen"},
	{Code: 110, Cat: 1, Name: "Mop the floor"},
	{Code: 111, Cat: 1, Name: "Dust the shelves"},
	{Code: 112, Cat: 1, Name: "Clean the bathroom"},
	{Code: 113, Cat: 1, Name: "Scrub the bathtub"},
	{Code: 114, Cat: 1, Name: "Clean the toilet"},
	{Code: 115, Cat: 1, Name: "Wipe the counters"},
	{Code: 116, Cat: 1, Name: "Clean the microwave"},
	{Code: 117, Cat: 1, Name: "Clean the fridge"},
	{Code: 118, Cat: 1, Name: "Fold the laundry"},
	{Code: 119, Cat: 1, Name: "Put away the laundry"},
	{Code: 120, Cat: 1, Name: "Start a load of laundry"},
	{Code: 121, Cat: 1, Name: "Change the bed sheets"},
	{Code: 122, Cat: 1, Name: "Make your bed"},
	{Code: 123, Cat: 1, Name: "Make everyone's beds"},
	{Code: 124, Cat: 1, Name: "Tidy your room"},
	{Code: 125, Cat: 1, Name: "Tidy the living room"},
	{Code: 126, Cat: 1, Name: "Pick up the toys"},
	{Code: 127, Cat: 1, Name: "Organise a closet"},
	{Code: 128, Cat: 1, Name: "Sort the recycling"},
	{Code: 129, Cat: 1, Name: "Water the houseplants"},
	{Code: 130, Cat: 1, Name: "Set the table"},
	{Code: 131, Cat: 1, Name: "Clear the table"},
	{Code: 132, Cat: 1, Name: "Wipe down the table"},
	{Code: 133, Cat: 1, Name: "Sort the mail"},
	{Code: 134, Cat: 1, Name: "Bring in the bins"},
	{Code: 135, Cat: 1, Name: "Put out the bins"},
	{Code: 136, Cat: 1, Name: "Clean a window"},
	{Code: 137, Cat: 1, Name: "Wipe the fingerprints off the door"},
	{Code: 138, Cat: 1, Name: "Match the socks"},
	{Code: 139, Cat: 1, Name: "Iron a shirt"},
	{Code: 140, Cat: 1, Name: "Polish shoes"},
	{Code: 141, Cat: 1, Name: "Wipe down the bannister"},
	{Code: 142, Cat: 1, Name: "Shake out the doormat"},
	{Code: 201, Cat: 2, Name: "Bake cookies"},
	{Code: 202, Cat: 2, Name: "Peanut butter cookies"},
	{Code: 203, Cat: 2, Name: "Chocolate chip cookies"},
	{Code: 204, Cat: 2, Name: "Bake a cake"},
	{Code: 205, Cat: 2, Name: "Bake brownies"},
	{Code: 206, Cat: 2, Name: "Bake muffins"},
	{Code: 207, Cat: 2, Name: "Make bread"},
	{Code: 208, Cat: 2, Name: "Make pancakes"},
	{Code: 209, Cat: 2, Name: "Make waffles"},
	{Code: 210, Cat: 2, Name: "Cook breakfast"},
	{Code: 211, Cat: 2, Name: "Cook lunch"},
	{Code: 212, Cat: 2, Name: "Cook dinner"},
	{Code: 213, Cat: 2, Name: "Make a sandwich"},
	{Code: 214, Cat: 2, Name: "Make a smoothie"},
	{Code: 215, Cat: 2, Name: "Make lemonade"},
	{Code: 216, Cat: 2, Name: "Make hot chocolate"},
	{Code: 217, Cat: 2, Name: "Make popcorn"},
	{Code: 218, Cat: 2, Name: "Pack a lunch"},
	{Code: 219, Cat: 2, Name: "Help with the groceries"},
	{Code: 220, Cat: 2, Name: "Put away the groceries"},
	{Code: 221, Cat: 2, Name: "Write the shopping list"},
	{Code: 222, Cat: 2, Name: "Chop vegetables"},
	{Code: 223, Cat: 2, Name: "Stir the pot"},
	{Code: 224, Cat: 2, Name: "A slice of cake"},
	{Code: 225, Cat: 2, Name: "A bowl of ice cream"},
	{Code: 226, Cat: 2, Name: "A candy bar"},
	{Code: 227, Cat: 2, Name: "A bag of chips"},
	{Code: 228, Cat: 2, Name: "A soda"},
	{Code: 229, Cat: 2, Name: "A juice box"},
	{Code: 230, Cat: 2, Name: "Pick the dinner"},
	{Code: 231, Cat: 2, Name: "Pick the restaurant"},
	{Code: 232, Cat: 2, Name: "Dessert first"},
	{Code: 233, Cat: 2, Name: "Second helping of dessert"},
	{Code: 234, Cat: 2, Name: "Breakfast in bed"},
	{Code: 301, Cat: 3, Name: "Mow the lawn"},
	{Code: 302, Cat: 3, Name: "Rake the leaves"},
	{Code: 303, Cat: 3, Name: "Bag the leaves"},
	{Code: 304, Cat: 3, Name: "Shovel the snow"},
	{Code: 305, Cat: 3, Name: "Salt the walkway"},
	{Code: 306, Cat: 3, Name: "Pull the weeds"},
	{Code: 307, Cat: 3, Name: "Water the garden"},
	{Code: 308, Cat: 3, Name: "Plant something"},
	{Code: 309, Cat: 3, Name: "Trim the hedge"},
	{Code: 310, Cat: 3, Name: "Sweep the porch"},
	{Code: 311, Cat: 3, Name: "Sweep the driveway"},
	{Code: 312, Cat: 3, Name: "Wash the car"},
	{Code: 313, Cat: 3, Name: "Vacuum the car"},
	{Code: 314, Cat: 3, Name: "Clean the garage"},
	{Code: 315, Cat: 3, Name: "Stack the firewood"},
	{Code: 316, Cat: 3, Name: "Pick up sticks in the yard"},
	{Code: 317, Cat: 3, Name: "Clean the gutters"},
	{Code: 318, Cat: 3, Name: "Wash the windows outside"},
	{Code: 319, Cat: 3, Name: "Sweep the patio"},
	{Code: 320, Cat: 3, Name: "Fill the bird feeder"},
	{Code: 321, Cat: 3, Name: "Check the mailbox"},
	{Code: 322, Cat: 3, Name: "Help in the garden"},
	{Code: 323, Cat: 3, Name: "Hose down the bins"},
	{Code: 401, Cat: 4, Name: "Walk the dog"},
	{Code: 402, Cat: 4, Name: "Feed the dog"},
	{Code: 403, Cat: 4, Name: "Feed the cat"},
	{Code: 404, Cat: 4, Name: "Feed the fish"},
	{Code: 405, Cat: 4, Name: "Clean the litter box"},
	{Code: 406, Cat: 4, Name: "Clean the cage"},
	{Code: 407, Cat: 4, Name: "Clean the fish tank"},
	{Code: 408, Cat: 4, Name: "Brush the dog"},
	{Code: 409, Cat: 4, Name: "Bathe the dog"},
	{Code: 410, Cat: 4, Name: "Pick up after the dog"},
	{Code: 411, Cat: 4, Name: "Play with the dog"},
	{Code: 412, Cat: 4, Name: "Refill the water bowl"},
	{Code: 413, Cat: 4, Name: "Take the dog to the park"},
	{Code: 414, Cat: 4, Name: "Pet sitting for a day"},
	{Code: 415, Cat: 4, Name: "Trim the dog's nails"},
	{Code: 501, Cat: 5, Name: "One hour of Switch time"},
	{Code: 502, Cat: 5, Name: "Half an hour of Switch time"},
	{Code: 503, Cat: 5, Name: "One hour of tablet time"},
	{Code: 504, Cat: 5, Name: "One hour of computer time"},
	{Code: 505, Cat: 5, Name: "One hour of TV"},
	{Code: 506, Cat: 5, Name: "Pick the movie"},
	{Code: 507, Cat: 5, Name: "Pick the show"},
	{Code: 508, Cat: 5, Name: "Control of the remote"},
	{Code: 509, Cat: 5, Name: "A game of chess"},
	{Code: 510, Cat: 5, Name: "A game of cards"},
	{Code: 511, Cat: 5, Name: "A board game together"},
	{Code: 512, Cat: 5, Name: "A video game together"},
	{Code: 513, Cat: 5, Name: "Player two for an hour"},
	{Code: 514, Cat: 5, Name: "Extra screen time"},
	{Code: 515, Cat: 5, Name: "Movie night"},
	{Code: 516, Cat: 5, Name: "Game night"},
	{Code: 517, Cat: 5, Name: "A round of mini golf"},
	{Code: 518, Cat: 5, Name: "A trip to the arcade"},
	{Code: 519, Cat: 5, Name: "Skip a turn losing at a game"},
	{Code: 601, Cat: 6, Name: "A LEGO set"},
	{Code: 602, Cat: 6, Name: "Old LEGO, by the bag"},
	{Code: 603, Cat: 6, Name: "A stuffed animal"},
	{Code: 604, Cat: 6, Name: "An action figure"},
	{Code: 605, Cat: 6, Name: "A trading card"},
	{Code: 606, Cat: 6, Name: "A pack of trading cards"},
	{Code: 607, Cat: 6, Name: "A book"},
	{Code: 608, Cat: 6, Name: "A comic book"},
	{Code: 609, Cat: 6, Name: "A puzzle"},
	{Code: 610, Cat: 6, Name: "A board game"},
	{Code: 611, Cat: 6, Name: "Art supplies"},
	{Code: 612, Cat: 6, Name: "A drawing"},
	{Code: 613, Cat: 6, Name: "A painting"},
	{Code: 614, Cat: 6, Name: "A craft you made"},
	{Code: 615, Cat: 6, Name: "A friendship bracelet"},
	{Code: 616, Cat: 6, Name: "Stickers"},
	{Code: 617, Cat: 6, Name: "A notebook"},
	{Code: 618, Cat: 6, Name: "Pens and pencils"},
	{Code: 619, Cat: 6, Name: "A toy car"},
	{Code: 620, Cat: 6, Name: "A ball"},
	{Code: 621, Cat: 6, Name: "A bike, borrowed for a day"},
	{Code: 622, Cat: 6, Name: "A scooter, borrowed for a day"},
	{Code: 623, Cat: 6, Name: "Headphones, borrowed"},
	{Code: 624, Cat: 6, Name: "A shirt"},
	{Code: 625, Cat: 6, Name: "Something from the attic"},
	{Code: 701, Cat: 7, Name: "Help with homework"},
	{Code: 702, Cat: 7, Name: "Help with maths homework"},
	{Code: 703, Cat: 7, Name: "Help with reading"},
	{Code: 704, Cat: 7, Name: "Help with spelling"},
	{Code: 705, Cat: 7, Name: "Help with a science project"},
	{Code: 706, Cat: 7, Name: "Quiz me for a test"},
	{Code: 707, Cat: 7, Name: "Practice spelling words"},
	{Code: 708, Cat: 7, Name: "Practice maths facts"},
	{Code: 709, Cat: 7, Name: "Read a chapter out loud"},
	{Code: 710, Cat: 7, Name: "Read a bedtime story"},
	{Code: 711, Cat: 7, Name: "Listen to me read"},
	{Code: 712, Cat: 7, Name: "Practice an instrument"},
	{Code: 713, Cat: 7, Name: "Practice piano for half an hour"},
	{Code: 714, Cat: 7, Name: "Proofread something"},
	{Code: 715, Cat: 7, Name: "Teach me something"},
	{Code: 716, Cat: 7, Name: "Help with a school poster"},
	{Code: 717, Cat: 7, Name: "Type something up"},
	{Code: 718, Cat: 7, Name: "Pack the school bag"},
	{Code: 719, Cat: 7, Name: "Sign the reading log"},
	{Code: 720, Cat: 7, Name: "A week of no reminders about homework"},
	{Code: 801, Cat: 8, Name: "Babysitting for an hour"},
	{Code: 802, Cat: 8, Name: "Babysitting for an evening"},
	{Code: 803, Cat: 8, Name: "Watch my sibling"},
	{Code: 804, Cat: 8, Name: "A ride somewhere"},
	{Code: 805, Cat: 8, Name: "A ride to a friend's house"},
	{Code: 806, Cat: 8, Name: "A ride to practice"},
	{Code: 807, Cat: 8, Name: "Take my turn at a chore"},
	{Code: 808, Cat: 8, Name: "Swap chores for a day"},
	{Code: 809, Cat: 8, Name: "Cover my dish night"},
	{Code: 810, Cat: 8, Name: "Help carry something heavy"},
	{Code: 811, Cat: 8, Name: "Help move furniture"},
	{Code: 812, Cat: 8, Name: "Help build something"},
	{Code: 813, Cat: 8, Name: "Fix something broken"},
	{Code: 814, Cat: 8, Name: "Hang a picture"},
	{Code: 815, Cat: 8, Name: "Assemble a toy"},
	{Code: 816, Cat: 8, Name: "Wrap a present"},
	{Code: 817, Cat: 8, Name: "Write a thank-you note"},
	{Code: 818, Cat: 8, Name: "Make a birthday card"},
	{Code: 819, Cat: 8, Name: "Help with a party"},
	{Code: 820, Cat: 8, Name: "Set up for a party"},
	{Code: 821, Cat: 8, Name: "Clean up after a party"},
	{Code: 822, Cat: 8, Name: "Take photos"},
	{Code: 823, Cat: 8, Name: "Find something that is lost"},
	{Code: 824, Cat: 8, Name: "Charge everyone's devices"},
	{Code: 825, Cat: 8, Name: "Answer the door for a delivery"},
	{Code: 826, Cat: 8, Name: "Water the plants while away"},
	{Code: 827, Cat: 8, Name: "Collect the post while away"},
	{Code: 828, Cat: 8, Name: "A hug"},
	{Code: 829, Cat: 8, Name: "A compliment"},
	{Code: 830, Cat: 8, Name: "An apology"},
	{Code: 901, Cat: 9, Name: "Stay up half an hour late"},
	{Code: 902, Cat: 9, Name: "Stay up an hour late"},
	{Code: 903, Cat: 9, Name: "Sleep in"},
	{Code: 904, Cat: 9, Name: "A day off chores"},
	{Code: 905, Cat: 9, Name: "A week off one chore"},
	{Code: 906, Cat: 9, Name: "Skip one chore"},
	{Code: 907, Cat: 9, Name: "Front seat of the car"},
	{Code: 908, Cat: 9, Name: "Pick the music in the car"},
	{Code: 909, Cat: 9, Name: "Choose the weekend outing"},
	{Code: 910, Cat: 9, Name: "A friend over"},
	{Code: 911, Cat: 9, Name: "A sleepover"},
	{Code: 912, Cat: 9, Name: "A trip to the park"},
	{Code: 913, Cat: 9, Name: "A trip to the library"},
	{Code: 914, Cat: 9, Name: "A trip to the pool"},
	{Code: 915, Cat: 9, Name: "A trip for ice cream"},
	{Code: 916, Cat: 9, Name: "A bike ride together"},
	{Code: 917, Cat: 9, Name: "A walk together"},
	{Code: 918, Cat: 9, Name: "One-on-one time with a parent"},
	{Code: 919, Cat: 9, Name: "Breakfast out"},
	{Code: 920, Cat: 9, Name: "Pick the bedtime story"},
	{Code: 921, Cat: 9, Name: "The good chair"},
	{Code: 922, Cat: 9, Name: "The big bedroom for a week"},
	{Code: 923, Cat: 9, Name: "Go first"},
	{Code: 924, Cat: 9, Name: "A pass on losing an argument"},
	{Code: 1001, Cat: 10, Name: "Allowance"},
	{Code: 1002, Cat: 10, Name: "Weekly allowance"},
	{Code: 1003, Cat: 10, Name: "Bonus for good work"},
	{Code: 1004, Cat: 10, Name: "Birthday money"},
	{Code: 1005, Cat: 10, Name: "A gift"},
	{Code: 1006, Cat: 10, Name: "Paying back a loan"},
	{Code: 1007, Cat: 10, Name: "Lending money"},
	{Code: 1008, Cat: 10, Name: "Splitting the cost"},
	{Code: 1009, Cat: 10, Name: "A fine"},
	{Code: 1010, Cat: 10, Name: "A refund"},
	{Code: 1011, Cat: 10, Name: "$1 of real cash", Currency: "USD", MinorUnits: 100},
	{Code: 1012, Cat: 10, Name: "$5 of real cash", Currency: "USD", MinorUnits: 500},
	{Code: 1013, Cat: 10, Name: "$10 of real cash", Currency: "USD", MinorUnits: 1000},
	{Code: 1014, Cat: 10, Name: "$20 of real cash", Currency: "USD", MinorUnits: 2000},
	{Code: 1015, Cat: 10, Name: "Saving up"},
	{Code: 1016, Cat: 10, Name: "Thanks"},
	{Code: 1017, Cat: 10, Name: "Sorry"},
	{Code: 1018, Cat: 10, Name: "Something else"},
}

// Lookup returns the item with a code, and whether it exists.
//
// Binary search over a sorted array in flash: no map, because a map would
// be built in RAM at startup and this table never changes.
func Lookup(code uint16) (*Item, bool) {
	lo, hi := 0, len(Items)-1
	for lo <= hi {
		mid := int(uint(lo+hi) >> 1)
		switch {
		case Items[mid].Code == code:
			return &Items[mid], true
		case Items[mid].Code < code:
			lo = mid + 1
		default:
			hi = mid - 1
		}
	}
	return nil, false
}

// Name returns an item's name, or "" for an unknown code.
func Name(code uint16) string {
	if it, ok := Lookup(code); ok {
		return it.Name
	}
	return ""
}

// Valid reports whether a code names a real item. Zero means "no code".
func Valid(code uint16) bool {
	if code == 0 {
		return false
	}
	_, ok := Lookup(code)
	return ok
}
