"""Generate the catalog for both halves of NanaCoin from catalog.json.

    python catalog/gen.py

Writes:
    internal/catalog/catalog.go                     the board and desktop server
    ../nanacoin_ui/src/app/catalog/catalog.ts       the client

# Why generated rather than hand-written twice

A code is what the ledger stores. If 202 means "Peanut butter cookies" in the
client and something else in the server, every record carrying 202 is quietly
wrong, and nothing fails loudly enough to notice. One source of truth removes
that failure mode entirely.

# Why the Go side is arrays of constants

The board keeps the catalog in flash, not RAM. Go string constants and a slice
of structs built at compile time live in the read-only data section, so 250
names cost flash - which the S3 has 16MB of - and no heap, which it has very
little of. Nothing here is allocated at startup.
"""

import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO_ROOT = os.path.dirname(ROOT)

GO_OUT = os.path.join(ROOT, "internal", "catalog", "catalog.go")
TS_OUT = os.path.join(REPO_ROOT, "nanacoin_ui", "src", "app", "catalog", "catalog.ts")


def load():
    with io.open(os.path.join(HERE, "catalog.json"), encoding="utf-8") as f:
        data = json.load(f)

    items = data["items"]
    cats = data["categories"]

    # The checks that matter, because each failure is silent at runtime.
    codes = [i["code"] for i in items]
    if len(codes) != len(set(codes)):
        dupes = sorted({c for c in codes if codes.count(c) > 1})
        sys.exit("duplicate codes: %s" % dupes)

    cat_ids = {c["id"] for c in cats}
    for i in items:
        if i["cat"] not in cat_ids:
            sys.exit("item %d references unknown category %d" % (i["code"], i["cat"]))
        if not (0 < i["code"] < 65536):
            sys.exit("code %d does not fit in a uint16" % i["code"])

    items.sort(key=lambda i: i["code"])
    cats.sort(key=lambda c: c["id"])
    return data, items, cats


def go_string(s):
    return json.dumps(s, ensure_ascii=False)


def write_go(data, items, cats):
    out = []
    w = out.append
    w("// Code generated by catalog/gen.py from catalog/catalog.json. DO NOT EDIT.")
    w("")
    w("// Package catalog is the fixed list of standard things a household trades.")
    w("//")
    w("// A listing stores a Code - a uint16 - instead of a title, which is the")
    w("// point: the text lives in flash as a compile-time constant rather than in")
    w("// the 12KiB RAM arena, so a listing for a standard thing costs two bytes")
    w("// and a listing with a custom title costs what it always did.")
    w("//")
    w("// Codes are permanent. Never renumber or reuse one: a code is what the")
    w("// ledger stores, and an old record carrying a reused code would silently")
    w("// mean something new.")
    w("package catalog")
    w("")
    w("// Version of the catalog data these tables were generated from.")
    w("const Version = %d" % data["version"])
    w("")
    w("// Category groups items for browsing.")
    w("type Category struct {")
    w("\tID   uint8")
    w("\tSlug string")
    w("\tName string")
    w("}")
    w("")
    w("// Item is one standard thing. Currency and MinorUnits are set only on the")
    w("// entries that stand for real money, e.g. \"$5 of real cash\".")
    w("type Item struct {")
    w("\tCode       uint16")
    w("\tCat        uint8")
    w("\tName       string")
    w("\tCurrency   string")
    w("\tMinorUnits int64")
    w("}")
    w("")

    w("// Categories, ordered by ID.")
    w("var Categories = [...]Category{")
    for c in cats:
        w("\t{ID: %d, Slug: %s, Name: %s}," % (c["id"], go_string(c["slug"]), go_string(c["name"])))
    w("}")
    w("")

    w("// Items, ordered by Code so Lookup can binary search.")
    w("var Items = [...]Item{")
    for i in items:
        parts = ["Code: %d" % i["code"], "Cat: %d" % i["cat"], "Name: %s" % go_string(i["name"])]
        if i.get("currency"):
            parts.append("Currency: %s" % go_string(i["currency"]))
        if i.get("minor_units"):
            parts.append("MinorUnits: %d" % i["minor_units"])
        w("\t{%s}," % ", ".join(parts))
    w("}")
    w("")

    w("// Lookup returns the item with a code, and whether it exists.")
    w("//")
    w("// Binary search over a sorted array in flash: no map, because a map would")
    w("// be built in RAM at startup and this table never changes.")
    w("func Lookup(code uint16) (*Item, bool) {")
    w("\tlo, hi := 0, len(Items)-1")
    w("\tfor lo <= hi {")
    w("\t\tmid := int(uint(lo+hi) >> 1)")
    w("\t\tswitch {")
    w("\t\tcase Items[mid].Code == code:")
    w("\t\t\treturn &Items[mid], true")
    w("\t\tcase Items[mid].Code < code:")
    w("\t\t\tlo = mid + 1")
    w("\t\tdefault:")
    w("\t\t\thi = mid - 1")
    w("\t\t}")
    w("\t}")
    w("\treturn nil, false")
    w("}")
    w("")
    w("// Name returns an item's name, or \"\" for an unknown code.")
    w("func Name(code uint16) string {")
    w("\tif it, ok := Lookup(code); ok {")
    w("\t\treturn it.Name")
    w("\t}")
    w("\treturn \"\"")
    w("}")
    w("")
    w("// Valid reports whether a code names a real item. Zero means \"no code\".")
    w("func Valid(code uint16) bool {")
    w("\tif code == 0 {")
    w("\t\treturn false")
    w("\t}")
    w("\t_, ok := Lookup(code)")
    w("\treturn ok")
    w("}")
    w("")

    os.makedirs(os.path.dirname(GO_OUT), exist_ok=True)
    with io.open(GO_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    return GO_OUT


def write_ts(data, items, cats):
    out = []
    w = out.append
    w("// Code generated by catalog/gen.py from catalog/catalog.json. DO NOT EDIT.")
    w("")
    w("// The fixed list of standard things a household trades.")
    w("//")
    w("// A listing stores a code rather than a title, so the same table has to")
    w("// exist on both sides - and has to agree. Generating both from one file is")
    w("// what makes that guaranteed rather than hoped for: a code meaning two")
    w("// different things would corrupt every record carrying it, silently.")
    w("")
    w("export const CATALOG_VERSION = %d;" % data["version"])
    w("")
    w("export interface Category {")
    w("  id: number;")
    w("  slug: string;")
    w("  name: string;")
    w("}")
    w("")
    w("export interface CatalogItem {")
    w("  code: number;")
    w("  cat: number;")
    w("  name: string;")
    w("  /** Set only on entries standing for real money. */")
    w("  currency?: string;")
    w("  minorUnits?: number;")
    w("}")
    w("")

    w("export const CATEGORIES: readonly Category[] = [")
    for c in cats:
        w("  { id: %d, slug: %s, name: %s }," % (c["id"], json.dumps(c["slug"]), json.dumps(c["name"], ensure_ascii=False)))
    w("];")
    w("")

    w("export const ITEMS: readonly CatalogItem[] = [")
    for i in items:
        parts = ["code: %d" % i["code"], "cat: %d" % i["cat"], "name: %s" % json.dumps(i["name"], ensure_ascii=False)]
        if i.get("currency"):
            parts.append("currency: %s" % json.dumps(i["currency"]))
        if i.get("minor_units"):
            parts.append("minorUnits: %d" % i["minor_units"])
        w("  { %s }," % ", ".join(parts))
    w("];")
    w("")

    w("/** Every item by code, built once. */")
    w("const BY_CODE = new Map<number, CatalogItem>(ITEMS.map((i) => [i.code, i]));")
    w("")
    w("export function lookup(code: number): CatalogItem | undefined {")
    w("  return BY_CODE.get(code);")
    w("}")
    w("")
    w("/** An item's name, or '' for a code this build does not know. */")
    w("export function catalogName(code: number): string {")
    w("  return BY_CODE.get(code)?.name ?? '';")
    w("}")
    w("")
    w("export function categoryOf(code: number): Category | undefined {")
    w("  const item = BY_CODE.get(code);")
    w("  return item ? CATEGORIES.find((c) => c.id === item.cat) : undefined;")
    w("}")
    w("")

    os.makedirs(os.path.dirname(TS_OUT), exist_ok=True)
    with io.open(TS_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    return TS_OUT


def main():
    data, items, cats = load()
    go = write_go(data, items, cats)
    ts = write_ts(data, items, cats)
    print("%d items, %d categories" % (len(items), len(cats)))
    print("  %s" % os.path.relpath(go, ROOT))
    print("  %s" % os.path.relpath(ts, ROOT))


if __name__ == "__main__":
    main()
