// SHA-256, for when the browser will not lend us its own.
//
// # Why this exists
//
// PKCE needs S256: the client hashes its verifier and sends the digest. The
// obvious way is `crypto.subtle.digest`, and that is what this client used.
//
// `crypto.subtle` is only defined in a **secure context** - https, or
// localhost. NanaCoin is served over plain http from a board on the LAN, at
// an IP or an mDNS name, and neither of those is a secure context. So
// `crypto.subtle` is `undefined` there and the login threw a TypeError before
// a single request was made. The symptom was "Something went wrong." with no
// failed request to find, because nothing had reached the network.
//
// TLS is not the answer on a household board: it would mean a domain, a
// certificate and a TLS stack on a microcontroller whose RAM is already the
// binding constraint. See nanacoin_web/README.md.
//
// So: a small SHA-256 in plain TypeScript, used only when the platform's own
// is unavailable. `crypto.getRandomValues` is *not* restricted to secure
// contexts, so the verifier itself is still generated by the platform CSPRNG -
// this file only replaces the hash, which is a public transformation of a
// value the client already has.
//
// Correctness matters more than speed here: it runs twice per login on a
// 43-character input. It is checked against the known SHA-256 test vectors in
// sha256.spec.ts, and against crypto.subtle itself wherever that exists.

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
  0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
  0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
  0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
  0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
  0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
  0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
  0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);

function rotr(x: number, n: number): number {
  return (x >>> n) | (x << (32 - n));
}

/** SHA-256 of a byte array, as 32 bytes. */
export function sha256(input: Uint8Array): Uint8Array {
  const h = new Uint32Array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c,
    0x1f83d9ab, 0x5be0cd19,
  ]);

  // Pad: a 1 bit, then zeros, then the length in bits as a 64-bit big-endian
  // integer, to a multiple of 64 bytes.
  const bitLen = input.length * 8;
  const withPad = new Uint8Array((((input.length + 8) >> 6) + 1) << 6);
  withPad.set(input);
  withPad[input.length] = 0x80;

  // The length goes in the last 8 bytes. Only the low 32 bits are written
  // from a number; anything longer than 512MB is not a PKCE verifier.
  const view = new DataView(withPad.buffer);
  view.setUint32(withPad.length - 4, bitLen >>> 0, false);
  view.setUint32(withPad.length - 8, Math.floor(bitLen / 0x100000000), false);

  const w = new Uint32Array(64);

  for (let offset = 0; offset < withPad.length; offset += 64) {
    for (let i = 0; i < 16; i++) w[i] = view.getUint32(offset + i * 4, false);
    for (let i = 16; i < 64; i++) {
      const s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ (w[i - 15] >>> 3);
      const s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ (w[i - 2] >>> 10);
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) >>> 0;
    }

    let [a, b, c, d, e, f, g, hh] = h;

    for (let i = 0; i < 64; i++) {
      const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = (e & f) ^ (~e & g);
      const temp1 = (hh + S1 + ch + K[i] + w[i]) >>> 0;
      const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = (a & b) ^ (a & c) ^ (b & c);
      const temp2 = (S0 + maj) >>> 0;

      hh = g;
      g = f;
      f = e;
      e = (d + temp1) >>> 0;
      d = c;
      c = b;
      b = a;
      a = (temp1 + temp2) >>> 0;
    }

    h[0] = (h[0] + a) >>> 0;
    h[1] = (h[1] + b) >>> 0;
    h[2] = (h[2] + c) >>> 0;
    h[3] = (h[3] + d) >>> 0;
    h[4] = (h[4] + e) >>> 0;
    h[5] = (h[5] + f) >>> 0;
    h[6] = (h[6] + g) >>> 0;
    h[7] = (h[7] + hh) >>> 0;
  }

  const out = new Uint8Array(32);
  const outView = new DataView(out.buffer);
  for (let i = 0; i < 8; i++) outView.setUint32(i * 4, h[i], false);
  return out;
}

/**
 * SHA-256 using the platform's implementation where it exists.
 *
 * `crypto.subtle` is absent on an insecure origin, which is every way this
 * app is actually served: an IP address or an mDNS name over plain http. The
 * fallback above keeps login working there rather than throwing before the
 * first request.
 */
export async function digestSha256(input: Uint8Array): Promise<Uint8Array> {
  if (typeof crypto !== 'undefined' && crypto.subtle) {
    const buf = await crypto.subtle.digest('SHA-256', input as BufferSource);
    return new Uint8Array(buf);
  }
  return sha256(input);
}

/** Whether the platform's own SHA-256 is available. */
export function hasNativeDigest(): boolean {
  return typeof crypto !== 'undefined' && !!crypto.subtle;
}
